### PUT request to update a patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174002
Content-Type: application/json

{
  "name": "Alice Johnson Ji",
  "email": "alice.johnsonn@example.com",
  "address": "789 Oak St, Capital City",
  "dateOfBirth": "1978-03-12"
}

###